services:

  mcp:

    build: .

    container_name: devmate-mcp

    working_dir: /app

    volumes:
      - .:/app

    env_file:
      - .env

    command: python mcp_server/server.py

    ports:
      - "8000:8000"


  backend:

    build: .

    container_name: devmate-backend

    working_dir: /app

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - mcp

    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8080

    ports:
      - "8080:8080"